default:
    trainer: ppo
    batch_size: 128
    beta: 5.0e-3
    buffer_size: 2048
    epsilon: 0.1
    gamma: 0.99
    hidden_units: 64
    lambd: 0.99
    learning_rate: 3.0e-3
    max_steps: 5.0e5
    memory_size: 256
    normalize: false
    num_epoch: 2
    num_layers: 1
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: true
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128

